# Generated by Django 5.2.4 on 2025-07-23 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/posts/')),
                ('title', models.CharField(max_length=60)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000000)),
            ],
        ),
    ]
