# Generated by Django 5.2.4 on 2025-07-31 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_alter_post_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish_date']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_publish_afe0c2_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['publish_date'], name='posts_post_publish_fbbd6e_idx'),
        ),
    ]
