# Generated by Django 5.2.4 on 2025-07-31 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 7, 31, 17, 24, 45, 638281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 7, 31, 17, 24, 45, 638308, tzinfo=datetime.timezone.utc)),
        ),
    ]
