"""
Django settings for pyblog project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-97*!kxsygu1jm*jv#oc3w*3)hd@@#yo@nm1pfu#*szw3g6q5ud"

# SECURITY WARNING: don't run with debug turned on in production!

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "posts",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pyblog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pyblog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DEBUG = "RENDER" not in os.environ

SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-97*!kxsygu1jm*jv#oc3w*3)hd@@#yo@nm1pfu#*szw3g6q5ud"
)

ALLOWED_HOSTS = [os.environ.get("RENDER_EXTERNAL_HOSTNAME"), "localhost", "127.0.0.1"]

DATABASES = {
    "default": dj_database_url.config(default="sqlite:///db.sqlite3", conn_max_age=600)
}


# Email settings
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # For development, use console backend to print emails to console
EMAIL_HOST = "smtp.gmail.com"  # e.g., 'smtp.gmail.com' or your hosting's SMTP
EMAIL_PORT = 587  # Often 587 for TLS, or 465 for SSL
EMAIL_USE_TLS = True  # Use True for TLS, False for SSL (and usually port 465)
EMAIL_HOST_USER = (
    "meez.sabra@gmail.com"  # The email address that will send the messages
)
EMAIL_HOST_PASSWORD = "11"  # The password for the sending email
DEFAULT_FROM_EMAIL = "no-reply@meezsrealms.com"  # Used as the "From" address if not specified in send_mail
CONTACT_EMAIL = (
    "meez.sabra.111@gmail.com"  # The email address where you want to receive messages
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Authentication URLs
LOGIN_REDIRECT_URL = "profile"  # URL name to redirect to after successful login
LOGOUT_REDIRECT_URL = "login"  # URL name to redirect to after logout
LOGIN_URL = "login"  # URL name for the login page (used by @login_required decorator)


USE_TZ = True

TIME_ZONE = "Asia/Riyadh"
